### ISSUE TITLE
BUGS as of Sep.19th 2021

### ISSUE THREAD

**Issue by WayGold** [WayGold/Rapid_Frogger#9]
@wzy31124513 Need some help with these if you have time tmr, I won't be available till late night tmr, I will see what I can do tmr night, thx
- [x] Player could not jump to a platform at next level/row while diving
- [x] Player will be picked up by a platform while diving
- [x] Player could not enter dive mode by hitting space while on a platform
- [x] Player could jump forward into diving mode while on a platform 
- [x] Timer cause game to crash when the time is over

**Comment by wzy31124513** [comment]
OK, I'll try to do it tomorrow

**Comment by WayGold** [comment]
@wzy31124513 All Bugs fixed
